import { NgModule } from '@angular/core';

import { CdkTableModule } from '@angular/cdk/table';
import * as Material from '@angular/material';

@NgModule({
  imports: [
    Material.MatAutocompleteModule,
    Material.MatButtonModule,
    Material.MatButtonToggleModule,
    Material.MatCardModule,
    Material.MatCheckboxModule,
    Material.MatChipsModule,
    Material.MatDatepickerModule,
    Material.MatDialogModule,
    Material.MatExpansionModule,
    Material.MatFormFieldModule,
    Material.MatGridListModule,
    Material.MatIconModule,
    Material.MatInputModule,
    Material.MatListModule,
    Material.MatMenuModule,
    Material.MatNativeDateModule,
    Material.MatPaginatorModule,
    Material.MatProgressBarModule,
    Material.MatProgressSpinnerModule,
    Material.MatRadioModule,
    Material.MatRippleModule,
    Material.MatSelectModule,
    Material.MatSidenavModule,
    Material.MatSliderModule,
    Material.MatSlideToggleModule,
    Material.MatSnackBarModule,
    Material.MatStepperModule,
    Material.MatSortModule,
    Material.MatTableModule,
    Material.MatTabsModule,
    Material.MatToolbarModule,
    Material.MatTooltipModule,
    CdkTableModule
  ],
  exports: [
    Material.MatAutocompleteModule,
    Material.MatButtonModule,
    Material.MatButtonToggleModule,
    Material.MatCardModule,
    Material.MatCheckboxModule,
    Material.MatChipsModule,
    Material.MatDatepickerModule,
    Material.MatDialogModule,
    Material.MatExpansionModule,
    Material.MatGridListModule,
    Material.MatIconModule,
    Material.MatInputModule,
    Material.MatListModule,
    Material.MatMenuModule,
    Material.MatNativeDateModule,
    Material.MatPaginatorModule,
    Material.MatProgressBarModule,
    Material.MatProgressSpinnerModule,
    Material.MatRadioModule,
    Material.MatRippleModule,
    Material.MatSelectModule,
    Material.MatSidenavModule,
    Material.MatSliderModule,
    Material.MatSlideToggleModule,
    Material.MatSnackBarModule,
    Material.MatStepperModule,
    Material.MatSortModule,
    Material.MatTableModule,
    Material.MatTabsModule,
    Material.MatToolbarModule,
    Material.MatTooltipModule,
    CdkTableModule
  ],
  declarations: []
})
export class MaterialModule { }
